blank_issues_enabled: false
contact_links:
  - name: Hulp en ondersteuning
    url: https://teams.microsoft.com/l/channel/19%3AWKO-qzPeC_1wX-GiRmz8SKcH86AmsKHEGWGkgQDCSdQ1%40thread.tacv2/Agency?groupId=96c39548-7965-4a84-b991-829c124f6db8&tenantId=0907bb1e-21fc-476f-8843-02d09ceb59a7&ngc=true&allowXTenantAccess=true
    about: Stel vragen a.u.b. via de interne MS Teams omgeving
  
